### ISSUE TITLE
Error finding the css file

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/skeleton-navigation-kendo#1]
This ought to be something trivial, but I am not energized this late to think about it. I am getting this error
```
GET http://localhost:9000/dist/basic-grid.css 404 (Not Found)A @ system.src.js:4703(anonymous function) @ system.src.js:4703Promise @ shim.min.js:1847(anonymous function) @ system.src.js:4703(anonymous function) @ system.src.js:4703(anonymous function) @ system.src.js:4703(anonymous function) @ system.src.js:4703(anonymous function) @ system.src.js:4703(anonymous function) @ system.src.js:4703(anonymous function) @ system.src.js:4703(anonymous function) @ system.src.js:4703h @ shim.min.js:1773(anonymous function) @ shim.min.js:1778e @ shim.min.js:1958
aurelia-logging-console.js:62 ERROR [app-router] Error: XHR error (404 Not Found) loading http://localhost:9000/dist/basic-grid.css
	Error loading http://localhost:9000/dist/basic-grid.css!http://localhost:9000/jspm_packages/github/systemjs/plugin-text@0.0.3.js
    at o (http://localhost:9000/jspm_packages/system.js:4:12894)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:9000/jspm_packages/system.js:4:13482)
```
when clicking on the KendoUI grid tab of this app

![image](https://cloud.githubusercontent.com/assets/2712405/12044463/ce2748e0-ae5f-11e5-9dd3-af76d6440553.png)

Since **[this css](https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo/blob/master/src/basic-grid.css)** does not show up in the `dist` folder, the problem ought to be somewhere in **[paths](https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo/blob/master/build/paths.js)** or **[here](https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo/blob/master/build/tasks/build.js#L34-L40)**

**Comment by adriatic** [comment]
Solved by bcb470c
